app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
avanzu_admin:
    resource: "@AvanzuAdminThemeBundle/Resources/config/routes.yml"
